# Generated by Django 6.0 on 2025-12-10 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(default='Waiting to start...', max_length=255)),
                ('result_content', models.TextField(blank=True, null=True)),
                ('output_format', models.CharField(default='txt', max_length=10)),
            ],
        ),
    ]
